name: publish

on:
  push:
    tags:
      - v*

jobs:
  call-publish-workflow:
    uses: deanmarcussen/NuGet-Publishing-GitHub-Actions/.github/workflows/publish.yml@v0.0.1
    with:
      project: ./Lombiq.HelpfulLibraries.Targets/Lombiq.HelpfulLibraries.Targets.csproj
      ref: ${GITHUB_REF}
      apikey: ${{ secrets.LOMBIQ_CLOUDSMITH_API_KEY }}
