name: publish

on:
  push:
    tags:
      - v*

jobs:
  call-publish-workflow:
    uses: Lombiq/NuGet-Publishing-GitHub-Actions/.github/workflows/publish.yml@v1
    with:
      source: https://nuget.cloudsmith.io/lombiq/Helpful-Libraries/v3/index.json
    secrets:
      apikey: ${{ secrets.LOMBIQ_CLOUDSMITH_API_KEY }}
