name: publish

on:
  push:
    tags:
      - v*

jobs:
  call-publish-workflow:
    uses: Lombiq/NuGet-Publishing-GitHub-Actions/.github/workflows/publish.yml@v1
    secrets:
      apikey: ${{ secrets.DEFAULT_PUBLISH_API_KEY }}
