name: publish

on:
  push:
    tags:
      - v*

jobs:
  call-publish-workflow:
    uses: deanmarcussen/NuGet-Publishing-GitHub-Actions/.github/workflows/publish.yml@v1
    secrets:
      apikey: ${{ secrets.LOMBIQ_CLOUDSMITH_API_KEY }}
